### PR TITLE
Fix icon_support for supporting dojo 1.9.0

### PR DESCRIPTION
**Pull request by allencblee**
For supporting dojo 1.9.0

### CODE REVIEW

**Comment by martinpengellyphillips** [comment]
Thanks for this. Have you checked the changes against Dojo 1.8 as well?

**Comment by allencblee** [comment]
Just updated it to make it downward compatible with Dojo 1.8

**Comment by martinpengellyphillips** [comment]
Just took a look at Dojo 1.9 and it seems that `_attachTemplateNodes` is now defined in `_AttachMixin` so might be better to do the override there (using a conditional require).

Let me know what you think.

**Comment by allencblee** [comment]
For some reason, I'm under the impression that conditional require is a bit slower.  The current implementation is probably the fastest approach.

**Comment by martinpengellyphillips** [comment]
Hmmm. My concern is more that `_AttachMixin` seems to be providing new functionality so we should probably patch it there to avoid clobbering completely. I'll take a look, but if I don't get anywhere fast I'll merge this in.

Meanwhile, do you want to issue a separate pull request for the timepicker styling fix to get that merged independently of this?

**Comment by allencblee** [comment]
Sorry, I deleted my fork accidentally.  Pls ignore this pull request.   I'll submit the timepicker styling separately.

**Pull request closed without merging**
