### PR TITLE
14 integration guide

### PR DESCRIPTION
**Pull request by martinpengellyphillips**
Have reworked the build system and packages to separate out the theme from its demo gallery. In addition have updated the README to give more information on integration.

### CODE REVIEW

**Comment by Mennodebrie** [comment]
Works great, just had to use 

<blockquote>
<dl>
<dt>require(['dbootstrap/main', ...], function(dbootstrap) {</dt>
<dd>// Start application.</dd>
</dl>
<p>});</p>
</blockquote>

instead of <blockquote>

<dl>
<dt>require(['dbootstrap', ...], function(dbootstrap) {</dt>
<dd>// Start application.</dd>
</dl>

<p>});</p>

</blockquote>

as described in the README

**Comment by martinpengellyphillips** [comment]
Thanks for testing. That is a little weird though as I believe the Dojo require system should automatically look for a main.js file if a package is required.

**Comment by shanto** [comment]
Worked flawlessly for me. Thanks a lot @thesociable for looking into and working on this!

@Mennodebrie, you need to declare (tell dojo about) the dbootstrap package before you "require" it. Only then, it will work out main.js automatically. For me, having this in dojo's config json string helped:

``` json
'packages': [
    ...,
    {
        location:"/static/dbootstrap/build/theme/dbootstrap",
        name:"dbootstrap"
    }
]
```

**Comment by martinpengellyphillips** [comment]
Thanks for the feedback - have updated the README with that information.

**Pull request merged**
